import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar/Navbar";
import Content from "../components/Content/Content";
import season from "../components/Content/Content.module.css";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.mainContainer} ${season.season1}`}>
        <Navbar />
        <Content />
      </div>
    </div>
  );
}
